version: '3.8'

services:
  backend:
    image: ghcr.io/polkanoval/pizza-shop-backend:latest
    container_name: pizza-backend
    restart: always
    expose:
      - "8000"
    volumes:
      # Файл базы данных в корне проекта
      - ./db.sqlite3:/app/db.sqlite3
      # Совмещаем с STATIC_ROOT = BASE_DIR / 'static'
      - static_volume:/app/static
      # Совмещаем с MEDIA_ROOT = BASE_DIR / 'media'
      - ./media:/app/media
    deploy:
      resources:
        limits:
          memory: 256M
    logging: &default-logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ghcr.io/polkanoval/pizza-shop-frontend:latest
    container_name: pizza-frontend
    restart: always
    expose:
      - "80"
    deploy:
      resources:
        limits:
          memory: 128M
    logging: *default-logging

  nginx:
    image: nginx:stable-alpine
    container_name: pizza-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Конфиг Nginx
      - ./nginx/conf/prod.conf:/etc/nginx/conf.d/default.conf
      # SSL сертификаты
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Пути для Nginx (должны быть прописаны как alias в prod.conf)
      - static_volume:/var/www/staticfiles:ro
      - ./media:/var/www/media:ro
    depends_on:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          memory: 64M
    logging: *default-logging

volumes:
  static_volume:
  media_volume: