services:
  backend:
    image: ghcr.io/polkanoval/pizza-shop-backend:latest
    container_name: pizza-backend
    restart: always
    # Убираем ports 8000:8000, чтобы никто не зашел в обход Nginx
    expose:
      - "8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      # Добавляем монтирование именованных томов для статики и медиа
      - static_volume:/var/www/polkanoval-project/backend/backend/staticfiles
      - media_volume:/var/www/polkanoval-project/backend/backend/media
    deploy:
      resources:
        limits:
          memory: 256M
    logging: &default-logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ghcr.io/polkanoval/pizza-shop-frontend:latest
    container_name: pizza-frontend
    restart: always
    # Убираем 8080:80, фронтенд будет доступен только через Nginx на 80/443
    expose:
      - "80"
    deploy:
      resources:
        limits:
          memory: 128M
    logging: *default-logging

  nginx:
    image: nginx:stable-alpine
    container_name: pizza-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Наш единственный конфиг из папки deploy
      - ./nginx/conf/prod.conf:/etc/nginx/conf.d/default.conf
      # Проброс сертификатов Certbot с вашего сервера
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Монтируем те же именованные тома в Nginx (только для чтения: ro)
      - static_volume:/var/www/polkanoval-project/backend/backend/staticfiles:ro
      - media_volume:/var/www/polkanoval-project/backend/backend/media:ro
    depends_on:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          memory: 64M
    logging: *default-logging

# Определяем именованные тома в конце файла
volumes:
  static_volume:
  media_volume: