services:
  # Брокер сообщений для Celery
  redis:
    image: redis:7-alpine
    container_name: pizza-redis
    restart: always
    logging: &default-logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: ghcr.io/polkanoval/pizza-shop-backend:latest
    container_name: pizza-backend
    restart: always
    expose:
      - "8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
      - ./media:/app/media
      # Синхронизация времени
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 256M
    logging: *default-logging

  # Воркер — меняет статусы заказов
  celery-worker:
    image: ghcr.io/polkanoval/pizza-shop-backend:latest
    container_name: pizza-celery-worker
    # Фикс заторов: concurrency, честное распределение и мониторинг событий
    command: celery -A backend worker --loglevel=info --concurrency=4 -Ofair --prefetch-multiplier=1 -E
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      # Синхронизация времени (Критично для выполнения countdown)
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis
      - backend
    deploy:
      resources:
        limits:
          memory: 256M
    logging: *default-logging

  # Бит — создает заказы по расписанию
  celery-beat:
    image: ghcr.io/polkanoval/pizza-shop-backend:latest
    container_name: pizza-celery-beat
    command: celery -A backend beat --loglevel=info
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 128M
    logging: *default-logging

  frontend:
    image: ghcr.io/polkanoval/pizza-shop-frontend:latest
    container_name: pizza-frontend
    restart: always
    expose:
      - "80"
    deploy:
      resources:
        limits:
          memory: 128M
    logging: *default-logging

  nginx:
    image: nginx:stable-alpine
    container_name: pizza-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/var/www/staticfiles:ro
      - ./media:/var/www/media:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          memory: 64M
    logging: *default-logging

volumes:
  static_volume:
  media_volume: