name: Manual Server Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ШАГ 1: Загружаем файлы репозитория
      - name: Checkout repository code
        uses: actions/checkout@v4

      # ШАГ 2: Добавляем ваш приватный SSH-ключ в SSH-агент раннера GitHub
      - name: Add SSH Key to Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # ШАГ 3: Копируем файлы по отдельности, без флага -r
      - name: Copy files via native SCP command
        run: |
          # Копируем docker-compose.yml
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/polkanoval-project/

          # Создаем целевую папку nginx/conf на сервере заранее!
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "mkdir -p /var/www/polkanoval-project/nginx/conf/"
          scp -o StrictHostKeyChecking=no nginx/conf/prod.conf ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/polkanoval-project/nginx/conf/

      # ШАГ 4: Запускаем SSH action ТОЛЬКО для выполнения команд НА СЕРВЕРЕ
      - name: Run deploy scripts on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/polkanoval-project
            # Авторизуемся в GHCR
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Скачиваем свежие образы
            docker compose pull

            # --- АВТОМАТИЧЕСКИЙ СБОР СТАТИЧЕСКИХ ФАЙЛОВ ---
            # Запуск collectstatic внутри контейнера Django
            # --noinput автоматически отвечает 'yes' на запрос
            docker compose run --rm backend python manage.py collectstatic --noinput
            # --- КОНЕЦ СБОРА СТАТИКИ ---

            # Запускаем все контейнеры (включая Nginx)
            docker compose up -d

            # Очистка: удаляем старые, неиспользуемые образы и кэш
            docker system prune -a -f