name: Manual Server Deploy

on:
  workflow_dispatch: # Это позволяет запускать деплой вручную через UI GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Переходим в папку на сервере, где лежит docker-compose.yml
            cd /var/www/polkanoval-project

            # Используем ваш Personal Access Token (GHCR_TOKEN), добавленный в секреты репозитория
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Скачиваем свежие образы из GHCR
            docker compose pull

            # Перезапускаем контейнеры с новыми образами
            docker compose up -d

            # Очистка: удаляем старые, неиспользуемые образы и кэш
            docker system prune -a -f