name: Manual Server Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Add SSH Key to Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via native SCP command
        run: |
          # Проверяем наличие файлов с правильным путем
          file docker-compose.yml nginx/conf/prod.conf # <-- ПУТЬ ИСПРАВЛЕН ЗДЕСЬ

          # Копируем файлы с правильным путем
          scp -o StrictHostKeyChecking=no -r docker-compose.yml nginx/conf/prod.conf ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/polkanoval-project/ # <-- ПУТЬ ИСПРАВЛЕН ЗДЕСЬ

      - name: Run deploy scripts on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/polkanoval-project
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d
            docker system prune -a -f